name: Docker Image CI

on:
  push:
    branches: [ dockerbuild ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd contrib/packaging/dockerfile && sh try-all.sh
